//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aircraft_Cabins
    {
        public int AircraftID { get; set; }
        public int Row { get; set; }
        public int Seat { get; set; }
    
        public virtual Aircrafts Aircrafts { get; set; }
    }
}
