//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int TicketID { get; set; }
        public int FlightID { get; set; }
        public string Userlogin { get; set; }
        public int Row { get; set; }
        public int Seat { get; set; }
        public int Price { get; set; }
        public System.TimeSpan Departure_Time { get; set; }
    
        public virtual Flights Flights { get; set; }
        public virtual Passengers Passengers { get; set; }
    }
}
